export const CHANGE_ROUTE = 'CHANGE_ROUTE';

export const CHANGE_SIGNIN_EMAIL = 'CHANGE_SIGNIN_EMAIL';
export const CHANGE_SIGNIN_PASSWORD = 'CHANGE_SIGNIN_PASSWORD';

export const USER_CHANGE_ID = 'USER_CHANGE_ID';
// export const USER_CHANGE_EMAIL = 'USER_CHANGE_EMAIL';
export const USER_CHANGE_NAME = 'USER_CHANGE_NAME';
export const USER_CHANGE_STATUS = 'USER_CHANGE_STATUS';
