// route
export const CHANGE_ROUTE = 'CHANGE_ROUTE';

// signIn
export const CHANGE_SIGNIN_EMAIL = 'CHANGE_SIGNIN_EMAIL';
export const CHANGE_SIGNIN_PASSWORD = 'CHANGE_SIGNIN_PASSWORD';

// signUp
export const CHANGE_SIGNUP_NAME = 'CHANGE_SIGNUP_NAME';
export const CHANGE_SIGNUP_EMAIL = 'CHANGE_SIGNUP_EMAIL';
export const CHANGE_SIGNUP_PASSWORD = 'CHANGE_SIGNUP_PASSWORD';
export const CHANGE_SIGNUP_RPASSWORD = 'CHANGE_SIGNUP_RPASSWORD';

// user
export const USER_LOAD_USER = 'USER_LOAD_USER';
export const USER_CHANGE_ID = 'USER_CHANGE_ID';
export const USER_CHANGE_NAME = 'USER_CHANGE_NAME';
export const USER_CHANGE_STATUS = 'USER_CHANGE_STATUS';
export const USER_CHANGE_FRIENDS = 'USER_CHANGE_FRIENDS';

// input
export const CHANGE_INPUT_FRIENDS = 'CHANGE_INPUT_FRIENDS';
export const CHANGE_USER_PROFILE = 'CHANGE_USER_PROFILE';
export const CHANGE_INPUT_USERS = 'CHANGE_INPUT_USERS';

// texting
export const TEXTING_SET_USER = 'TEXTING_SET_USER';