// route
export const CHANGE_ROUTE = 'CHANGE_ROUTE';

// signIn
export const CHANGE_SIGNIN_EMAIL = 'CHANGE_SIGNIN_EMAIL';
export const CHANGE_SIGNIN_PASSWORD = 'CHANGE_SIGNIN_PASSWORD';

// user
export const USER_LOAD_USER = 'USER_LOAD_USER';
export const USER_CHANGE_ID = 'USER_CHANGE_ID';
export const USER_CHANGE_NAME = 'USER_CHANGE_NAME';
export const USER_CHANGE_STATUS = 'USER_CHANGE_STATUS';
export const USER_CHANGE_FRIENDS = 'USER_CHANGE_FRIENDS';

// input
export const CHANGE_INPUT_FRIENDS = 'CHANGE_INPUT_FRIENDS';

// texting
export const TEXTING_SET_USER = 'TEXTING_SET_USER';